client_id = "9a925b70fdd4b2de6df6791dd1f0e2b7"
name = "Imam Recovery OS"
application_url = "https://shopify-recovery-os.vercel.app"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

[access_scopes]
scopes = "write_products, write_customers, write_orders, write_draft_orders, write_content, write_files, write_themes, write_metaobject_definitions, write_metaobjects, write_inventory, write_locations, read_legal_policies, write_shipping, write_discounts, write_translations, write_online_store_navigation, write_price_rules, write_locales"

[auth]
redirect_urls = [ "https://shopify-recovery-os.vercel.app/api/auth/callback" ]


[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://shopify-recovery-os.vercel.app/api/webhooks"

[webhooks.privacy_compliance]
customer_deletion_url = "https://shopify-recovery-os.vercel.app/api/webhooks/customers-redact"
customer_data_request_url = "https://shopify-recovery-os.vercel.app/api/webhooks/customers-data-request"
shop_deletion_url = "https://shopify-recovery-os.vercel.app/api/webhooks/shop-redact"