graph TD
  stepBackup["stepBackup"] --> recovery_packagesDB[("recovery_packages")]
  stepBackup["stepBackup"] --> backupsDB[("backups")]
  stepBackup["stepBackup"] --> backup_resourcesDB[("backup_resources")]
  stepBackup["stepBackup"] --> activity_logDB[("activity_log")]
  handleDownload["handleDownload"] --> backupsDB[("backups")]
  handleDownload["handleDownload"] --> recovery_packagesDB[("recovery_packages")]
  generateRestorePlan["generateRestorePlan"] --> backupsDB[("backups")]
  generateRestorePlan["generateRestorePlan"] --> restore_jobsDB[("restore_jobs")]
  generateRestorePlan["generateRestorePlan"] --> activity_logDB[("activity_log")]
  generateRestorePlan["generateRestorePlan"] --> recovery_packagesDB[("recovery_packages")]
  executeRestoreStep["executeRestoreStep"] --> backupsDB[("backups")]
  executeRestoreStep["executeRestoreStep"] --> restore_jobsDB[("restore_jobs")]
  executeRestoreStep["executeRestoreStep"] --> activity_logDB[("activity_log")]
  executeRestoreStep["executeRestoreStep"] --> recovery_packagesDB[("recovery_packages")]
  enqueueJob["enqueueJob"] --> jobsDB[("jobs")]
  enqueueJob["enqueueJob"] --> job_logsDB[("job_logs")]
  logJobEvent["logJobEvent"] --> jobsDB[("jobs")]
  logJobEvent["logJobEvent"] --> job_logsDB[("job_logs")]
  processNextJob["processNextJob"] --> jobsDB[("jobs")]
  processNextJob["processNextJob"] --> job_logsDB[("job_logs")]
  executeCleanMigrationEngine["executeCleanMigrationEngine"] --> conflict_intelligenceDB[("conflict_intelligence")]
  executeDeepCompareEngine["executeDeepCompareEngine"] --> deep_compare_resultsDB[("deep_compare_results")]
  generateStorePreparationReport["generateStorePreparationReport"] --> store_preparationsDB[("store_preparations")]
  generateAndStoreReports["generateAndStoreReports"] --> reportsDB[("reports")]
  generateAndStoreReports["generateAndStoreReports"] --> telemetryDB[("telemetry")]
  getAppCredentials["getAppCredentials"] --> oauth_sessionsDB[("oauth_sessions")]
  getAppCredentials["getAppCredentials"] --> storesDB[("stores")]
  getAppCredentials["getAppCredentials"] --> activity_logDB[("activity_log")]
  normalizeShop["normalizeShop"] --> oauth_sessionsDB[("oauth_sessions")]
  normalizeShop["normalizeShop"] --> storesDB[("stores")]
  normalizeShop["normalizeShop"] --> activity_logDB[("activity_log")]
  isValidShopDomain["isValidShopDomain"] --> oauth_sessionsDB[("oauth_sessions")]
  isValidShopDomain["isValidShopDomain"] --> storesDB[("stores")]
  isValidShopDomain["isValidShopDomain"] --> activity_logDB[("activity_log")]
  generateState["generateState"] --> oauth_sessionsDB[("oauth_sessions")]
  generateState["generateState"] --> storesDB[("stores")]
  generateState["generateState"] --> activity_logDB[("activity_log")]
  buildAuthorizeUrl["buildAuthorizeUrl"] --> oauth_sessionsDB[("oauth_sessions")]
  buildAuthorizeUrl["buildAuthorizeUrl"] --> storesDB[("stores")]
  buildAuthorizeUrl["buildAuthorizeUrl"] --> activity_logDB[("activity_log")]
  verifyCallbackHmac["verifyCallbackHmac"] --> oauth_sessionsDB[("oauth_sessions")]
  verifyCallbackHmac["verifyCallbackHmac"] --> storesDB[("stores")]
  verifyCallbackHmac["verifyCallbackHmac"] --> activity_logDB[("activity_log")]
  isTimestampFresh["isTimestampFresh"] --> oauth_sessionsDB[("oauth_sessions")]
  isTimestampFresh["isTimestampFresh"] --> storesDB[("stores")]
  isTimestampFresh["isTimestampFresh"] --> activity_logDB[("activity_log")]
  exchangeCodeForToken["exchangeCodeForToken"] --> oauth_sessionsDB[("oauth_sessions")]
  exchangeCodeForToken["exchangeCodeForToken"] --> storesDB[("stores")]
  exchangeCodeForToken["exchangeCodeForToken"] --> activity_logDB[("activity_log")]
  registerWebhooks["registerWebhooks"] --> oauth_sessionsDB[("oauth_sessions")]
  registerWebhooks["registerWebhooks"] --> storesDB[("stores")]
  registerWebhooks["registerWebhooks"] --> activity_logDB[("activity_log")]
  handleOAuthCallback["handleOAuthCallback"] --> oauth_sessionsDB[("oauth_sessions")]
  handleOAuthCallback["handleOAuthCallback"] --> storesDB[("stores")]
  handleOAuthCallback["handleOAuthCallback"] --> activity_logDB[("activity_log")]
  verifyWebhookHmac["verifyWebhookHmac"] --> storesDB[("stores")]
  handleShopifyWebhooks["handleShopifyWebhooks"] --> storesDB[("stores")]
  connectShopifyStore["connectShopifyStore"] --> storesDB[("stores")]
  connectShopifyStore["connectShopifyStore"] --> activity_logDB[("activity_log")]
  connectShopifyStore["connectShopifyStore"] --> oauth_sessionsDB[("oauth_sessions")]
  connectShopifyStore["connectShopifyStore"] --> backupsDB[("backups")]
  connectShopifyStore["connectShopifyStore"] --> backup_resourcesDB[("backup_resources")]
  connectShopifyStore["connectShopifyStore"] --> restore_jobsDB[("restore_jobs")]
  beginShopifyOAuth["beginShopifyOAuth"] --> storesDB[("stores")]
  beginShopifyOAuth["beginShopifyOAuth"] --> activity_logDB[("activity_log")]
  beginShopifyOAuth["beginShopifyOAuth"] --> oauth_sessionsDB[("oauth_sessions")]
  beginShopifyOAuth["beginShopifyOAuth"] --> backupsDB[("backups")]
  beginShopifyOAuth["beginShopifyOAuth"] --> backup_resourcesDB[("backup_resources")]
  beginShopifyOAuth["beginShopifyOAuth"] --> restore_jobsDB[("restore_jobs")]
  listStores["listStores"] --> storesDB[("stores")]
  listStores["listStores"] --> activity_logDB[("activity_log")]
  listStores["listStores"] --> oauth_sessionsDB[("oauth_sessions")]
  listStores["listStores"] --> backupsDB[("backups")]
  listStores["listStores"] --> backup_resourcesDB[("backup_resources")]
  listStores["listStores"] --> restore_jobsDB[("restore_jobs")]
  getStore["getStore"] --> storesDB[("stores")]
  getStore["getStore"] --> activity_logDB[("activity_log")]
  getStore["getStore"] --> oauth_sessionsDB[("oauth_sessions")]
  getStore["getStore"] --> backupsDB[("backups")]
  getStore["getStore"] --> backup_resourcesDB[("backup_resources")]
  getStore["getStore"] --> restore_jobsDB[("restore_jobs")]
  deleteStore["deleteStore"] --> storesDB[("stores")]
  deleteStore["deleteStore"] --> activity_logDB[("activity_log")]
  deleteStore["deleteStore"] --> oauth_sessionsDB[("oauth_sessions")]
  deleteStore["deleteStore"] --> backupsDB[("backups")]
  deleteStore["deleteStore"] --> backup_resourcesDB[("backup_resources")]
  deleteStore["deleteStore"] --> restore_jobsDB[("restore_jobs")]
  startBackup["startBackup"] --> storesDB[("stores")]
  startBackup["startBackup"] --> activity_logDB[("activity_log")]
  startBackup["startBackup"] --> oauth_sessionsDB[("oauth_sessions")]
  startBackup["startBackup"] --> backupsDB[("backups")]
  startBackup["startBackup"] --> backup_resourcesDB[("backup_resources")]
  startBackup["startBackup"] --> restore_jobsDB[("restore_jobs")]
  stepBackupFn["stepBackupFn"] --> storesDB[("stores")]
  stepBackupFn["stepBackupFn"] --> activity_logDB[("activity_log")]
  stepBackupFn["stepBackupFn"] --> oauth_sessionsDB[("oauth_sessions")]
  stepBackupFn["stepBackupFn"] --> backupsDB[("backups")]
  stepBackupFn["stepBackupFn"] --> backup_resourcesDB[("backup_resources")]
  stepBackupFn["stepBackupFn"] --> restore_jobsDB[("restore_jobs")]
  listBackups["listBackups"] --> storesDB[("stores")]
  listBackups["listBackups"] --> activity_logDB[("activity_log")]
  listBackups["listBackups"] --> oauth_sessionsDB[("oauth_sessions")]
  listBackups["listBackups"] --> backupsDB[("backups")]
  listBackups["listBackups"] --> backup_resourcesDB[("backup_resources")]
  listBackups["listBackups"] --> restore_jobsDB[("restore_jobs")]
  getBackup["getBackup"] --> storesDB[("stores")]
  getBackup["getBackup"] --> activity_logDB[("activity_log")]
  getBackup["getBackup"] --> oauth_sessionsDB[("oauth_sessions")]
  getBackup["getBackup"] --> backupsDB[("backups")]
  getBackup["getBackup"] --> backup_resourcesDB[("backup_resources")]
  getBackup["getBackup"] --> restore_jobsDB[("restore_jobs")]
  listRecentActivity["listRecentActivity"] --> storesDB[("stores")]
  listRecentActivity["listRecentActivity"] --> activity_logDB[("activity_log")]
  listRecentActivity["listRecentActivity"] --> oauth_sessionsDB[("oauth_sessions")]
  listRecentActivity["listRecentActivity"] --> backupsDB[("backups")]
  listRecentActivity["listRecentActivity"] --> backup_resourcesDB[("backup_resources")]
  listRecentActivity["listRecentActivity"] --> restore_jobsDB[("restore_jobs")]
  dashboardSummary["dashboardSummary"] --> storesDB[("stores")]
  dashboardSummary["dashboardSummary"] --> activity_logDB[("activity_log")]
  dashboardSummary["dashboardSummary"] --> oauth_sessionsDB[("oauth_sessions")]
  dashboardSummary["dashboardSummary"] --> backupsDB[("backups")]
  dashboardSummary["dashboardSummary"] --> backup_resourcesDB[("backup_resources")]
  dashboardSummary["dashboardSummary"] --> restore_jobsDB[("restore_jobs")]
  generateRestorePlanFn["generateRestorePlanFn"] --> storesDB[("stores")]
  generateRestorePlanFn["generateRestorePlanFn"] --> activity_logDB[("activity_log")]
  generateRestorePlanFn["generateRestorePlanFn"] --> oauth_sessionsDB[("oauth_sessions")]
  generateRestorePlanFn["generateRestorePlanFn"] --> backupsDB[("backups")]
  generateRestorePlanFn["generateRestorePlanFn"] --> backup_resourcesDB[("backup_resources")]
  generateRestorePlanFn["generateRestorePlanFn"] --> restore_jobsDB[("restore_jobs")]
  startRestoreFn["startRestoreFn"] --> storesDB[("stores")]
  startRestoreFn["startRestoreFn"] --> activity_logDB[("activity_log")]
  startRestoreFn["startRestoreFn"] --> oauth_sessionsDB[("oauth_sessions")]
  startRestoreFn["startRestoreFn"] --> backupsDB[("backups")]
  startRestoreFn["startRestoreFn"] --> backup_resourcesDB[("backup_resources")]
  startRestoreFn["startRestoreFn"] --> restore_jobsDB[("restore_jobs")]
  stepRestoreFn["stepRestoreFn"] --> storesDB[("stores")]
  stepRestoreFn["stepRestoreFn"] --> activity_logDB[("activity_log")]
  stepRestoreFn["stepRestoreFn"] --> oauth_sessionsDB[("oauth_sessions")]
  stepRestoreFn["stepRestoreFn"] --> backupsDB[("backups")]
  stepRestoreFn["stepRestoreFn"] --> backup_resourcesDB[("backup_resources")]
  stepRestoreFn["stepRestoreFn"] --> restore_jobsDB[("restore_jobs")]
  handleVerifyStoreBApi["handleVerifyStoreBApi"] --> storesDB[("stores")]
