graph TD
  Router["Application Router"]
  Router --> authtsx["auth.tsx"]
  Router --> indextsx["index.tsx"]
  Router --> backupsbackupIdtsx["backups.$backupId.tsx"]
  Router --> backupsindextsx["backups.index.tsx"]
  Router --> connecttsx["connect.tsx"]
  Router --> dashboardtsx["dashboard.tsx"]
  Router --> reportstsx["reports.tsx"]
  Router --> restoretsx["restore.tsx"]
  Router --> routetsx["route.tsx"]
  Router --> settingstsx["settings.tsx"]
  Router --> storesstoreIdtsx["stores.$storeId.tsx"]
  Router --> storesindextsx["stores.index.tsx"]
  Router --> __roottsx["__root.tsx"]
