/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMigrationRouteImport } from './routes/_authenticated/migration'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExtractionsIndexRouteImport } from './routes/_authenticated/extractions.index'
import { Route as AuthenticatedExtractionsExtractionIdRouteImport } from './routes/_authenticated/extractions.$extractionId'
import { Route as AuthenticatedRecoveryWizardRouteImport } from './routes/_authenticated/recovery/wizard'
import { Route as AuthenticatedStoresIndexRouteImport } from './routes/_authenticated/stores.index'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated/stores.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMigrationRoute = AuthenticatedMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtractionsIndexRoute =
  AuthenticatedExtractionsIndexRouteImport.update({
    id: '/extractions/',
    path: '/extractions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtractionsExtractionIdRoute =
  AuthenticatedExtractionsExtractionIdRouteImport.update({
    id: '/extractions/$extractionId',
    path: '/extractions/$extractionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecoveryWizardRoute =
  AuthenticatedRecoveryWizardRouteImport.update({
    id: '/recovery/wizard',
    path: '/recovery/wizard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresIndexRoute =
  AuthenticatedStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/stores/$storeId',
    path: '/stores/$storeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/extractions/$extractionId': typeof AuthenticatedExtractionsExtractionIdRoute
  '/recovery/wizard': typeof AuthenticatedRecoveryWizardRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/extractions/': typeof AuthenticatedExtractionsIndexRoute
  '/stores/': typeof AuthenticatedStoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/extractions/$extractionId': typeof AuthenticatedExtractionsExtractionIdRoute
  '/recovery/wizard': typeof AuthenticatedRecoveryWizardRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/extractions': typeof AuthenticatedExtractionsIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/migration': typeof AuthenticatedMigrationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/extractions/$extractionId': typeof AuthenticatedExtractionsExtractionIdRoute
  '/_authenticated/recovery/wizard': typeof AuthenticatedRecoveryWizardRoute
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/_authenticated/extractions/': typeof AuthenticatedExtractionsIndexRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/migration'
    | '/reports'
    | '/settings'
    | '/extractions/$extractionId'
    | '/recovery/wizard'
    | '/stores/$storeId'
    | '/extractions/'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/migration'
    | '/reports'
    | '/settings'
    | '/extractions/$extractionId'
    | '/recovery/wizard'
    | '/stores/$storeId'
    | '/extractions'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/connect'
    | '/_authenticated/dashboard'
    | '/_authenticated/migration'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/extractions/$extractionId'
    | '/_authenticated/recovery/wizard'
    | '/_authenticated/stores/$storeId'
    | '/_authenticated/extractions/'
    | '/_authenticated/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migration': {
      id: '/_authenticated/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof AuthenticatedMigrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extractions/': {
      id: '/_authenticated/extractions/'
      path: '/extractions'
      fullPath: '/extractions/'
      preLoaderRoute: typeof AuthenticatedExtractionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extractions/$extractionId': {
      id: '/_authenticated/extractions/$extractionId'
      path: '/extractions/$extractionId'
      fullPath: '/extractions/$extractionId'
      preLoaderRoute: typeof AuthenticatedExtractionsExtractionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recovery/wizard': {
      id: '/_authenticated/recovery/wizard'
      path: '/recovery/wizard'
      fullPath: '/recovery/wizard'
      preLoaderRoute: typeof AuthenticatedRecoveryWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof AuthenticatedStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMigrationRoute: typeof AuthenticatedMigrationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedExtractionsExtractionIdRoute: typeof AuthenticatedExtractionsExtractionIdRoute
  AuthenticatedRecoveryWizardRoute: typeof AuthenticatedRecoveryWizardRoute
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRoute
  AuthenticatedExtractionsIndexRoute: typeof AuthenticatedExtractionsIndexRoute
  AuthenticatedStoresIndexRoute: typeof AuthenticatedStoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMigrationRoute: AuthenticatedMigrationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedExtractionsExtractionIdRoute:
    AuthenticatedExtractionsExtractionIdRoute,
  AuthenticatedRecoveryWizardRoute: AuthenticatedRecoveryWizardRoute,
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRoute,
  AuthenticatedExtractionsIndexRoute: AuthenticatedExtractionsIndexRoute,
  AuthenticatedStoresIndexRoute: AuthenticatedStoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
